from app.models.models import (  # noqa: F401
    Calificacion,
    Carga,
    Documento,
    EmpresaPyme,
    Notificacion,
    Oferta,
    Pago,
    TrackingPosition,
    Transportista,
    TipoTarifa,
    User,
    Vehiculo,
    Viaje,
)
