from enum import StrEnum


class UserRole(StrEnum):
    ADMIN = "ADMIN"
    PYME = "PYME"
    TRANSPORTISTA = "TRANSPORTISTA"


class UserStatus(StrEnum):
    ACTIVO = "ACTIVO"
    PENDIENTE_VERIFICACION = "PENDIENTE_VERIFICACION"
    SUSPENDIDO = "SUSPENDIDO"


class TransportistaTipo(StrEnum):
    AUTONOMO = "AUTONOMO"
    EMPRESA_FAMILIAR = "EMPRESA_FAMILIAR"
    FLOTA_MEDIANA = "FLOTA_MEDIANA"


class VehiculoTipo(StrEnum):
    FURGON = "FURGON"
    SIDER = "SIDER"
    SEMIRREMOLQUE = "SEMIRREMOLQUE"
    CHASIS = "CHASIS"
    TERMICO = "TERMICO"
    TOLVA = "TOLVA"
    UTILITARIO = "UTILITARIO"


class VehiculoEstado(StrEnum):
    ACTIVO = "ACTIVO"
    PENDIENTE_VERIFICACION = "PENDIENTE_VERIFICACION"
    INACTIVO = "INACTIVO"


class OwnerTipo(StrEnum):
    EMPRESA = "EMPRESA"
    TRANSPORTISTA = "TRANSPORTISTA"
    VEHICULO = "VEHICULO"
    VIAJE = "VIAJE"


class DocumentoTipo(StrEnum):
    DNI = "DNI"
    CUIT = "CUIT"
    LICENCIA = "LICENCIA"
    SEGURO_CARGA = "SEGURO_CARGA"
    SEGURO_VEHICULO = "SEGURO_VEHICULO"
    POLIZA_CAUCION = "POLIZA_CAUCION"
    CARTA_PORTE = "CARTA_PORTE"
    REMITO = "REMITO"
    FACTURA = "FACTURA"
    COMPROBANTE_ENTREGA = "COMPROBANTE_ENTREGA"


class DocumentoEstado(StrEnum):
    PENDIENTE = "PENDIENTE"
    APROBADO = "APROBADO"
    RECHAZADO = "RECHAZADO"
    VENCIDO = "VENCIDO"


class CargaEstado(StrEnum):
    PUBLICADA = "PUBLICADA"
    CON_OFERTAS = "CON_OFERTAS"
    ASIGNADA = "ASIGNADA"
    EN_CURSO = "EN_CURSO"
    ENTREGADA = "ENTREGADA"
    CANCELADA = "CANCELADA"


class OfertaEstado(StrEnum):
    PENDIENTE = "PENDIENTE"
    ACEPTADA = "ACEPTADA"
    RECHAZADA = "RECHAZADA"
    CANCELADA = "CANCELADA"


class ViajeEstado(StrEnum):
    ASIGNADO = "ASIGNADO"
    EN_CAMINO_RETIRO = "EN_CAMINO_RETIRO"
    CARGA_RETIRADA = "CARGA_RETIRADA"
    EN_TRANSITO = "EN_TRANSITO"
    ENTREGADO = "ENTREGADO"
    CANCELADO = "CANCELADO"


class PagoEstado(StrEnum):
    PENDIENTE = "PENDIENTE"
    RETENIDO = "RETENIDO"
    LIBERADO = "LIBERADO"
    CANCELADO = "CANCELADO"


class PagoMetodo(StrEnum):
    SIMULADO = "SIMULADO"
    TRANSFERENCIA = "TRANSFERENCIA"
    EFECTIVO = "EFECTIVO"


class NotificacionTipo(StrEnum):
    NUEVA_OFERTA = "NUEVA_OFERTA"
    CARGA_ASIGNADA = "CARGA_ASIGNADA"
    CAMBIO_ESTADO_VIAJE = "CAMBIO_ESTADO_VIAJE"
    DOCUMENTO_RECHAZADO = "DOCUMENTO_RECHAZADO"
    PAGO_ACTUALIZADO = "PAGO_ACTUALIZADO"
